run:
  modules-download-mode: readonly

linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - decorder
    - errname
    - errorlint
    - funlen
    - gci
    - gocognit
    - gofmt
    - grouper
    - ineffassign
    - misspell
    - nestif
    - nilerr
    - nolintlint
    - unconvert
    - unparam
    - whitespace

linters-settings:
  funlen:
    statements: 50

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - errcheck