run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable-all: true
  disable:
    - exhaustruct
    - exhaustivestruct
    - wrapcheck

    - scopelint
    - golint
    - varcheck
    - interfacer
    - ifshort
    - deadcode
    - structcheck
    - nosnakecase
    - maligned

linters-settings:
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
      - T

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - funlen

    - source: 'ok bool'
      linters:
        - nonamedreturns
