name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v5.0.0
        
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.7.0    
      
      - name: Run tests
        run: go test -json ./... -covermode=atomic -coverprofile go_test_lit.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: go_test_lit.out
          
