name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3 
        with:
          install-mode: goinstall
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-go@v5.0.0
        with:
          go-version: '1.21'
      
      - name: Run tests
        run: go test -json ./... -covermode=atomic -coverprofile go_test_lit.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: go_test_lit.out
          
